config/routes.rb
Rails.application.routes.draw do
  root to: 'divisions#index'
  resources :divisions do
    member do
      post :add
    end
  end
  resources :employees do
    member do
      post :add
      post :remove
    end
  end
  resources :projects do
    member do
      post :add
      post :remove

    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/division.rb
class Division < ApplicationRecord
  has_many :employees, dependent: :nullify
  after_destroy :reset_id
  before_save :capitalize
  validates :name, presence: true

  def reset_id
    Employee.all.each do |employee|
      if employee.division_id == nil
        employee.update(:division_id => 0)
    end
  end
end

  def capitalize
    self.name = self.name.titleize()
  end

end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :division
  has_and_belongs_to_many :projects
  before_save :capitalize
  validates :employee_name, presence: true
  scope :no_division, -> { where(division_id: 0)}

  def capitalize
    self.employee_name = self.employee_name.titleize()
  end

end

app/models/project.rb
class Project < ApplicationRecord
  has_and_belongs_to_many :employees
  before_save :capitalize
  validates :project_name, presence: true


  def capitalize
    self.project_name = self.project_name.titleize()
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController

  def index

    @divisions = Division.all
    @employees = Employee.all - Employee.no_division
    @projects = Project.all
    :index
  end

  def new
    @division = Division.new
    :new
  end

  def create
    @division = Division.new(division_params)
    if @division.save
      flash[:notice] = "Division Created"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @division = Division.find(params[:id])
    :edit
  end

  def show
    @division = Division.find(params[:id])
    @employees = []
    Employee.all.each do |employee|
    if employee.division_id != @division.id
      @employees.push(employee.employee_name)
      end
    end
    :show
  end

  def update
    @division = Division.find(params[:id])
    if @division.update(division_params)
      flash[:notice] = "Division Update"
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @division = Division.find(params[:id])
    @division.destroy
    flash[:notice] = "Division Removed"
    redirect_to root_path
  end

  def add
    @division = Division.find(params[:id])
    employee = Employee.where(employee_name: params[:employee].fetch("employee")).first
    employee.update(:division_id => @division.id)
    flash[:notice] = "Employee Added"
    redirect_to division_path


  end

end


private
  def division_params
    params.require(:division).permit(:name)
  end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def new
    @employee = Employee.new
    :new
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      flash[:notice] = "Employee Created"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @employee = Employee.find(params[:id])
    @division_names = []
    Division.all.each do |division|
      @division_names.push(division.name)
    end
    :edit
  end

  def show
    @employee = Employee.find(params[:id])
    @projects = []
    Project.all.each do |project|
      if @employee.projects.exclude?(project)
      @projects.push(project.project_name)
      end
    end
    :show
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update(:employee_name => employee_params.fetch("employee_name"), :division_id => Division.where(name: employee_params.fetch("division_id")).first.id)
      flash[:notice] = "Employee Updated"
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    flash[:notice] = "Employee Removed"
    redirect_to root_path
  end

  def add
    @employee = Employee.find(params[:id])
    # Division.where(name: employee_params.fetch("division_id")).first.id)
    project = Project.where(project_name: params[:project].fetch("project")).first
    # binding.pry
    @employee.projects << project
    flash[:notice] = "Project Added"
    redirect_to employee_path

  end

  def remove

    @employee = Employee.find(params[:id])
    # Division.where(name: employee_params.fetch("division_id")).first.id)
    project = Project.find(params[:project_remove].fetch("project_id"))
    # binding.pry
    @employee.projects.delete(project)
    flash[:notice] = "Project Removed"
    redirect_to employee_path

  end

end


private
  def employee_params
    params.require(:employee).permit(:employee_name, :division_id)
  end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController


  def new
    @project = Project.new
    :new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = "Project Added"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
    :edit
  end

  def show
    @project = Project.find(params[:id])
    @employees = []
    Employee.all.each do |employee|
      if @project.employees.exclude?(employee)
        @employees.push(employee.employee_name)
      end
    end

    :show
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      flash[:notice] = "Project Updated"
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])

    @project.destroy
    flash[:notice] = "Projet Removed"
    redirect_to root_path
  end

  def add
    @project = Project.find(params[:id])
    # Division.where(name: employee_params.fetch("division_id")).first.id)
    employee = Employee.where(employee_name: params[:employee].fetch("employee")).first
    # binding.pry
    @project.employees << employee
    flash[:notice] = "Employee Added"
    redirect_to project_path

  end

  def remove

    @project = Project.find(params[:id])
    # Division.where(name: employee_params.fetch("division_id")).first.id)
    employee = Employee.find(params[:employee_remove].fetch("employee_id"))
    # binding.pry
    @project.employees.delete(employee)
    flash[:notice] = "Employee Removed"
    redirect_to project_path


  end

end


private
  def project_params
    params.require(:project).permit(:project_name)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/divisions/edit.html.erb
<h1>Edit division</h1>

<%= form_for @division do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/divisions/index.html.erb
<h2>Divisions</h2>
<p><%= link_to "Create new division", new_division_path %></p>

<% if @divisions.any? %>
<ul>
  <% @divisions.each do |division| %>
  <li><%= link_to division.name, division_path(division) %></li>
  <% end %>
</ul>
<% else %>
<p>There are no divisions yet.</p>
<% end %>


<h2>Employees</h2>
<p><%= link_to "Create new employee", new_employee_path %></p>
<% if @employees.any? %>

<ul>
  <% @employees.each do |employee| %>
  <li><%= link_to employee.employee_name, employee_path(employee) %></li>
  <% end %>
</ul>
<% else %>
<p>There are no employees yet.</p>
<% end %>
<% if Employee.no_division.any? %>
<h3>Employees Without Division</h3>
<ul>
  <% Employee.no_division.each do |employee| %>
  <li><%= link_to employee.employee_name, employee_path(employee) %></li>
  <% end %>
</ul>
<% else %>
<p>There are no employees yet.</p>
<% end %>


<h2>Projects</h2>
<p><%= link_to "Create new project", new_project_path %></p>
<% if @projects.any? %>
<ul>
  <% @projects.each do |project| %>
  <li><%= link_to project.project_name, project_path(project) %></li>
  <% end %>
</ul>
<% else %>
<p>There are no projects yet.</p>
<% end %>

app/views/divisions/new.html.erb
<h1>New Division</h1>

<%= form_for @division do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/divisions/show.html.erb
<h1><%= @division.name %></h1>
<h3>Employees:</h3>
<% if @division.employees.any? %>
<% @division.employees.each do |employee| %>
<p><%=employee.employee_name%></p>
<% end %>
<% else %>
<p>No employees in this division</p>
<% end %>


<% if @division.id != 0 %>

<p><%= link_to "Edit", edit_division_path(@division) %></p>
<p><%= link_to "Delete", division_path(@division),
  :data => {:confirm => "You sure?",
  :method => "delete"} %></p>



  <% else %>
  <p>You are not allowed to edit this division</p>



  <% end %>

  <%= form_for "employee", :url => {:action => "add"} do |f| %>
  <%= f.submit "Add Employee" %>
  <%= f.select :employee, @employees %>


  <% end %>

  <p><%= link_to "Return to divisions", divisions_path %></p>

app/views/employees/edit.html.erb
<h1>Edit Employee</h1>

<%= form_for @employee do |f| %>
  <%= f.label :employee_name %>
  <%= f.text_field :employee_name, :required => true %>
  <%= f.label :division_id %>
  <%= f.select :division_id, @division_names%>
  <%= f.submit  %>
<% end %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= form_for @employee do |f| %>
  <%= f.label :employee_name %>
  <%= f.text_field :employee_name %>
  <%= f.hidden_field :division_id, :value => 0%>


  <%= f.submit %>
<% end %>

app/views/employees/show.html.erb
<h1><%= @employee.employee_name %></h1>
<h2><%= @employee.division.name %></h2>

<h3>Projects:</h3>
<% if @employee.projects.any? %>
<% @employee.projects.each do |project| %>
<p><%=project.project_name%>
  <%= form_for "project_remove", :url => {:action => "remove"} do |f| %>
  <%= f.hidden_field :project_id, :value => project.id%>


  <%= f.submit "Take this employee off of the project"%>
<% end %>



</p>
<% end %>
<% else %>
<p>This employee has no projects</p>
<% end %>
<p><%= link_to "Edit", edit_employee_path(@employee) %></p>
<p><%= link_to "Delete", employee_path(@employee),
  :data => {:confirm => "You sure?",
  :method => "delete"} %></p>



  <%= form_for "project", :url => {:action => "add"} do |f| %>
  <%= f.submit "Add Project" %>
    <%= f.select :project, @projects %>
    <% end %>



  <p><%= link_to "Return to employees", root_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectEmployeeAppRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:alert] %>
  <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/projects/edit.html.erb
<h1>Edit project</h1>

<%= form_for @project do |f| %>
  <%= f.label :project_name %>
  <%= f.text_field :project_name %>
  <%= f.submit  %>
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= form_for @project do |f| %>
  <%= f.label :project_name %>
  <%= f.text_field :project_name %>


  <%= f.submit %>
<% end %>

app/views/projects/show.html.erb
<h1><%= @project.project_name %></h1>

<h3>Employees:</h3>
<% if @project.employees.any? %>
<% @project.employees.each do |employee| %>
<p><%=employee.employee_name%>

    <%= form_for "employee_remove", :url => {:action => "remove"} do |f| %>
    <%= f.hidden_field :employee_id, :value => employee.id%>


    <%= f.submit "Take this employee of the project"%>
  <% end %>

</p>
<% end %>
<% else %>
<p>No employees on this project</p>
<% end %>


<p><%= link_to "Edit", edit_project_path(@project) %></p>
<p><%= link_to "Delete", project_path(@project),
  :data => {:confirm => "You sure?",
  :method => "delete"} %></p>




  <p><%= link_to "Return to projects", projects_path %></p>


  <%= form_for "employee", :url => {:action => "add"} do |f| %>
  <%= f.submit "Add Employee" %>
    <%= f.select :employee, @employees %>


  <% end %>